### ISSUE TITLE
Is a username and password login possible (instead of email and password)?

### ISSUE THREAD

**Issue by durraniu** [kennedymwavu/frbs#1]
Thank you for this contribution. I plan to use your package to create custom login screen for my app.

I found that login with username is possible on Firebase as described [here](https://github.com/firebase/functions-samples/tree/main/Node-1st-gen/username-password-auth). Looking at the readme of {frbs}, it seems that only email sign up/in is possible. Is that correct or can I use username sign up/in also?

**Comment by kennedymwavu** [comment]
Hi @durraniu,
Username & password login is not yet supported by `{frbs}`, but may be included in future versions.
In the meantime, you can look at `{shinymanager}` for that functionality.

**Comment by durraniu** [comment]
I guess one hack is to still ask for email in addition to a username when registering, but only ask for the username when signing in. Or use the display name as username. Behind the scenes, I'd match the username with email and sign in with email.

**Comment by kennedymwavu** [comment]
Ah yes, that's one way to work around it.
What I had in my mind when creating the package was ensuring that the user emails are verified which is why I didn't go the username way.

**Comment by kennedymwavu** [comment]
@durraniu I believe your suggestion is actually a good solution.
1. Ask for email, username & password during registration.
2. Save the email & username to your database.
3. During sign in, if the user enters a username, match it to the email and use that to sign in to firebase.

Is it okay to mark this as closed?

**Comment by durraniu** [comment]
Yes, that solution is working for me.

**Comment by udurraniAtPresage** [comment]
Thinking about this more and looking in the documentation, I see `frbs_exchange_custom_token`. Does that mean I can use something like the `login` or `shinymanager` package to create new users with ID and password, generate a token, and then use `frbs_exchange_custom_token` to get a firebase token? This way password reset may be possible.

The constraint I have is that I can't ask for email at the time of registration for the purpose of anonymity. So, a hack like `<userID>@someCustomDomain.com` can be used to register a user, but the password reset becomes impossible if needed.

What do you think?

**Comment by kennedymwavu** [comment]
- Case 1:
How then will you know that the person asking for the password reset is the account owner? AFAIK, the main reason for requiring an email is:
  1. After sign up, user confirms via the verification email that they own the address.
  2. If the user ever needs password reset, we're sure that we're sending the reset link to the rightful owner.

- Case 2:
If you're going to store the user's login credentials (username & password), is there really any need for firebase? Because:
  1. You've already "handled" everything yourself.
  2. At the end of the day firebase will require an email so that it can send a reset link to the user.

As a side note, from my understanding of your statement:
> I can't ask for email at the time of registration for the purpose of anonymity

I believe anyone is able to access your application. My guess is that there is some part of the app that requires a user to have an account (eg. for persistent saving of progress). If that is the case, you can inform the user (eg. via a notification) that for their changes to be saved they need to login to their account or create one. After which you will, of course, ask for their email & password.

Please let me know if I have misunderstood your question.

**Comment by udurraniAtPresage** [comment]
You correctly pointed out that anyone can reset the password if email verification is not a requirement. Here was my idea to make sure that does not happen:

1. The users of my app are students and instructors. A requirement is to keep students completely private in the database. So, I don't ask for an email from users but generate an ID for them at the time of registration. The instructors use their emails as usual.
2. A student forgets their password. On the 'Reset Password' tab, they provide their existing ID and new password. This request for password reset is sent to their instructor.
3. The instructor confirms the password reset with student in class and approves it. Now, the student can use their new password.

I thought the above workflow was possible with `frbs::frbs_change_password`. But it requires the `id_token` which is provided only after a user is logged in. 

So, I started looking into alternative options where only a username/password login is possible without email. Stackoverflow tells me it could be possible with `signInWithCustomToken` as described [here](https://firebase.google.com/docs/auth/web/custom-auth). When I saw `frbs_exchange_custom_token`, I thought I could probably use it for authenticating with firebase. 

I guess that leads me to these questions:

- What is the purpose of `frbs_exchange_custom_token`?
- Do you have any ideas about this use-case? 

Thank you for taking the time to answer my questions and making it easy to use firebase.

**Comment by kennedymwavu** [comment]
I've done some digging and it turns out that firebase doesn't allow creation of custom tokens via REST. See [here](https://stackoverflow.com/questions/37408684/is-it-still-possible-to-do-server-side-verification-of-tokens-in-firebase-3?noredirect=1#comment62518682_37408684:~:text=working%20this%20out.-,Creating%20tokens%20or%20verifying%20them%20via%20REST,-This%20isn%27t%20supported). Not the outcome I had hoped for, but there's nothing much we can do about that.

Now I understand your use case. I believe you've handled it well by ensuring the instructor confirms the password reset with the student in class before approving it.  That now serves the purpose of email verification.

**Comment by udurraniAtPresage** [comment]
Oh, no REST API option is too bad.

The problem with my current setup is that the password reset email needs to be sent to ... an email 🙃. But I don't ask for email for student users. Rather, I generate ID for them.

I believe the only other option is to make my own authentication system based on a database. I don't think any other authentication package in shiny supports a custom authentication without email.

Thanks again for looking into this.

**Comment by kennedymwavu** [comment]
Anytime! All the best in your project.

**Comment by kennedymwavu** [comment]
Hello @durraniu,
This is late but it solves your initial problem.
We've added a new function [frbs_sign_in_anonymously()](https://github.com/kennedymwavu/frbs/blob/main/R/frbs_sign_in_anonymously.R) which (you guessed it right) you can use to sign in a user to firebase anonymously.

Here's a reprex:
```r
# create new user & sign them in anonymously:
user <- frbs_sign_in_anonymously()
user

# set password for the user:
new_password <- "<insert-user-password>"
res <- frbs_change_password(id_token = user$idToken, password = new_password)
res
```

I believe this is very close to (if not exactly) what you were looking for:
1. Sign in student anonymously
2. A student should be able to set a new password in case they forget the old one.

**Comment by kennedymwavu** [comment]
We've also added another function [frbs_change_email()](https://github.com/kennedymwavu/frbs/blob/main/R/frbs_change_email.R). Of course in your case you don't need a real email for the students, so your process might look something like this:

```r
# create new user & sign them in anonymously:
user <- frbs_sign_in_anonymously()
user

# set password for the user:
new_password <- "<insert-user-password>"
res <- frbs_change_password(id_token = user$idToken, password = new_password)

# you can set a fake email for the student.
# this will only work if you've disabled email enumeration protection in the
# firebase project.
user_with_email <- frbs_change_email(
  id_token = res$idToken,
  email = "fake@mail.com"
)

# sign in using the email & password:
frbs_sign_in(email = "fake@mail.com", password = new_password)
```

**Comment by durraniu** [comment]
Anonymous sign in is very useful, thanks. I am a little confused about changing password functionality after anonymous sign in. As I understand, `frbs_change_password` will change the password of the user whose `idToken` is provided. With `user <- frbs_sign_in_anonymously()`, how would firebase know who the user is with `user$idToken`? Whose password will be changed in this case?

**Comment by kennedymwavu** [comment]
It's why I included the step to change/set the email. Since the user is anonymous, you can generate a fake email which you will use to identify them.

But now in retrospect, this is similar to your previous approach, just with extra steps.

**Comment by udurraniAtPresage** [comment]
Thanks again for providing these options. I guess anonymous sign in can be used this way but could be less secure. Good to know that this option exists.
I found that Firebase Cloud Functions support HTTP requests. So, if I write a python/javascript cloud function (via admin SDK) to change password, I can make a HTTP request via {httr} to change a user password from shiny.

**Comment by kennedymwavu** [comment]
Yes, that's much better & secure.
