### ISSUE TITLE
frbs_sign_in does not return the displayName

### ISSUE THREAD

**Issue by durraniu** [kennedymwavu/frbs#2]
I am experimenting with the code in your `frbs-examples` repository. During registration I enter first and last name that I suppose make up the `displayName` that `frbs_sign_in` should return in the list. But it returns an empty string, e.g:

```
frbs::frbs_sign_in(email="xldevmkjjtqkpauzoe@cwmxc.com", password="examplepass")
$kind
[1] "identitytoolkit#VerifyPasswordResponse"

$localId
[1] "jtgfDxu7aFVSbsw1aejGu79G7Pn2"

$email
[1] "xldevmkjjtqkpauzoe@cwmxc.com"

$displayName
[1] ""
...
```
Is that intended behaviour?

**Comment by kennedymwavu** [comment]
Yes, that is the intended behaviour.
If you look at the reprex [here](https://github.com/kennedymwavu/frbs-examples/blob/2ea54d3bc4159b3d50f2596a92208955e9a13357/shiny/R/mod_auth_server.R#L116-L124), you will notice that I'm saving the display name in the database but firebase handles the sign in with only the email & password.

**Comment by durraniu** [comment]
You solved a huge problem for me! Thank you for adding those comments and the tip to add the user to the database. I wrote `user_exists()` and `create_user()`, and am now able to sign in users with username without asking for email.

**Comment by kennedymwavu** [comment]
- [x] Implement [update profile](https://firebase.google.com/docs/reference/rest/auth#section-update-profile):
    - display name
    - photo url
